### PR TITLE
Added refugee info url's 

### PR DESCRIPTION
**Pull request by chamibia**

### CODE REVIEW

**Comment by Guiso92** [comment]
@chamibia why is there a package-lock.json created? we are using yarn so that file shouldn't be created

**Comment by chamibia** [comment]
Oh, that was unintended. How can that be reverted?

**Comment by Guiso92** [comment]
you should delete the file and just do a "git commit --amend" to replace the commit that you did with a new one with that change

**Comment by Guiso92** [comment]
also you shouldn't need to modify the yarn.lock either so I think that's an error too. I'll say you need to do `rm -rf package-lock.json` `rm -rf yarn.lock` and `rm -rf node_modules` and then do a `yarn install`

**Comment by chamibia** [comment]
Got it! Will do that thanks

**Review by Guiso92 — CHANGES_REQUESTED** [review]
the only files you need to change are index.tsx and the logo

**Comment by chamibia** [comment]
those changes have been made

**Review by Guiso92 — APPROVED** [review]

**Comment by Guiso92** [comment]
before pushing this to the main branch you should create the instance in vercel so it get's deployed

**Comment by chamibia** [comment]
I'm having a problem importing the repository to vercel

**Pull request merged**
